// Code generated by protoc-gen-go. DO NOT EDIT.
// source: testrpc.proto

package testproto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type RPCRequest struct {
	Seq              *uint64 `protobuf:"varint,1,req,name=seq" json:"seq,omitempty"`
	Method           *string `protobuf:"bytes,2,req,name=method" json:"method,omitempty"`
	Arg              []byte  `protobuf:"bytes,3,opt,name=arg" json:"arg,omitempty"`
	NeedResp         *bool   `protobuf:"varint,4,opt,name=needResp" json:"needResp,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *RPCRequest) Reset()                    { *m = RPCRequest{} }
func (m *RPCRequest) String() string            { return proto.CompactTextString(m) }
func (*RPCRequest) ProtoMessage()               {}
func (*RPCRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{0} }

func (m *RPCRequest) GetSeq() uint64 {
	if m != nil && m.Seq != nil {
		return *m.Seq
	}
	return 0
}

func (m *RPCRequest) GetMethod() string {
	if m != nil && m.Method != nil {
		return *m.Method
	}
	return ""
}

func (m *RPCRequest) GetArg() []byte {
	if m != nil {
		return m.Arg
	}
	return nil
}

func (m *RPCRequest) GetNeedResp() bool {
	if m != nil && m.NeedResp != nil {
		return *m.NeedResp
	}
	return false
}

type RPCResponse struct {
	Seq              *uint64 `protobuf:"varint,1,req,name=seq" json:"seq,omitempty"`
	Err              *string `protobuf:"bytes,2,opt,name=err" json:"err,omitempty"`
	Ret              []byte  `protobuf:"bytes,3,opt,name=ret" json:"ret,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *RPCResponse) Reset()                    { *m = RPCResponse{} }
func (m *RPCResponse) String() string            { return proto.CompactTextString(m) }
func (*RPCResponse) ProtoMessage()               {}
func (*RPCResponse) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{1} }

func (m *RPCResponse) GetSeq() uint64 {
	if m != nil && m.Seq != nil {
		return *m.Seq
	}
	return 0
}

func (m *RPCResponse) GetErr() string {
	if m != nil && m.Err != nil {
		return *m.Err
	}
	return ""
}

func (m *RPCResponse) GetRet() []byte {
	if m != nil {
		return m.Ret
	}
	return nil
}

type Hello struct {
	Hello            *string `protobuf:"bytes,1,req,name=hello" json:"hello,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Hello) Reset()                    { *m = Hello{} }
func (m *Hello) String() string            { return proto.CompactTextString(m) }
func (*Hello) ProtoMessage()               {}
func (*Hello) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{2} }

func (m *Hello) GetHello() string {
	if m != nil && m.Hello != nil {
		return *m.Hello
	}
	return ""
}

type World struct {
	World            *string `protobuf:"bytes,1,req,name=world" json:"world,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *World) Reset()                    { *m = World{} }
func (m *World) String() string            { return proto.CompactTextString(m) }
func (*World) ProtoMessage()               {}
func (*World) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{3} }

func (m *World) GetWorld() string {
	if m != nil && m.World != nil {
		return *m.World
	}
	return ""
}

func init() {
	proto.RegisterType((*RPCRequest)(nil), "testproto.RPCRequest")
	proto.RegisterType((*RPCResponse)(nil), "testproto.RPCResponse")
	proto.RegisterType((*Hello)(nil), "testproto.hello")
	proto.RegisterType((*World)(nil), "testproto.world")
}

func init() { proto.RegisterFile("testrpc.proto", fileDescriptor1) }

var fileDescriptor1 = []byte{
	// 187 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x8d, 0x41, 0x4a, 0xc5, 0x30,
	0x10, 0x86, 0x49, 0x5a, 0xa5, 0x19, 0x15, 0x4a, 0x10, 0x09, 0x82, 0x10, 0xba, 0xca, 0xca, 0x4b,
	0xf4, 0x02, 0x32, 0x37, 0x10, 0x33, 0xd8, 0x45, 0x6d, 0xd2, 0x49, 0xc4, 0xeb, 0xcb, 0xe4, 0xb5,
	0x6f, 0xf5, 0x76, 0xdf, 0x97, 0x3f, 0xcc, 0x07, 0x4f, 0x95, 0x4a, 0xe5, 0xfc, 0xf5, 0x9e, 0x39,
	0xd5, 0x64, 0x8d, 0x68, 0xc3, 0x29, 0x02, 0xe0, 0xc7, 0x8c, 0xb4, 0xff, 0x52, 0xa9, 0x76, 0x84,
	0xae, 0xd0, 0xee, 0x94, 0xd7, 0xa1, 0x47, 0x41, 0xfb, 0x02, 0xf7, 0x3f, 0x54, 0x97, 0x14, 0x9d,
	0xf6, 0x3a, 0x18, 0x3c, 0x4c, 0x7e, 0x7e, 0xf2, 0xb7, 0xeb, 0xbc, 0x0a, 0x8f, 0x28, 0x68, 0x5f,
	0x61, 0xd8, 0x88, 0x22, 0x52, 0xc9, 0xae, 0xf7, 0x2a, 0x0c, 0x78, 0xf5, 0x69, 0x86, 0x87, 0x56,
	0x29, 0x39, 0x6d, 0x85, 0x6e, 0x64, 0x46, 0xe8, 0x88, 0xd9, 0x69, 0xaf, 0x82, 0x41, 0x41, 0x79,
	0x61, 0xaa, 0x67, 0x80, 0xa9, 0x4e, 0x6f, 0x70, 0xb7, 0xd0, 0xba, 0x26, 0xfb, 0x7c, 0x40, 0x3b,
	0x60, 0xf0, 0x22, 0x32, 0xff, 0x25, 0x5e, 0xa3, 0xcc, 0x0d, 0xce, 0xb9, 0xc9, 0x7f, 0x00, 0x00,
	0x00, 0xff, 0xff, 0x3f, 0x2b, 0x07, 0x48, 0x03, 0x01, 0x00, 0x00,
}
